### ISSUE TITLE
For ios is there a way to prevent screenshot and screen recorder because the one that you have provided doesnt do it

### ISSUE THREAD

**Issue by ankushdec1993** [hawkup/react-native-prevent-screenshot#1]

**Comment by ivks** [comment]
@ankushdec1993 ,
Did you guys find an alternative solution to this?

**Comment by hawkup** [comment]
I'm sorry to tell you that you can't prevent screen capture on iOS.

As a result of my research, I have suggested 2 methods
1. After the user capture screen (UIApplicationUserDidTakeScreenshot), send the capture event to the server or display a warning message.
2. Try ScreenShieldKit (https://screenshieldkit.com). You can read more from this article. https://medium.com/nomtek/screenshot-preventing-on-mobile-apps-9e62f51643e9

And sorry for the late reply

Referrences:
https://stackoverflow.com/a/48228319/1754750
https://medium.com/nomtek/screenshot-preventing-on-mobile-apps-9e62f51643e9
